# Generated by Django 5.2.6 on 2025-12-05 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Evento')),
                ('accion_realizada', models.CharField(choices=[('CREATE', 'Creación de Registro'), ('UPDATE', 'Actualización de Registro'), ('DELETE', 'Eliminación de Registro'), ('LOGIN_SUCCESS', 'Inicio de Sesión Exitoso'), ('LOGIN_FAILED', 'Intento de Inicio de Sesión Fallido'), ('LOGOUT', 'Cierre de Sesión'), ('ACCESS_DENIED', 'Intento de Acceso No Autorizado'), ('USER_BLOCKED', 'Usuario Bloqueado por Seguridad'), ('TOKEN_RECOVERY', 'Uso de Enlace de Recuperación de Contraseña')], max_length=50, verbose_name='Tipo de Evento Registrado')),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True, verbose_name="Modelo Afectado (Ej: 'Parto', 'Usuario')")),
                ('registro_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Registro Afectado')),
                ('detalles_cambio', models.TextField(blank=True, null=True, verbose_name="Detalles, Datos 'Antes' y 'Después', o Mensaje de Error")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP del Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Involucrado')),
            ],
            options={
                'verbose_name': 'Registro de Trazabilidad y Auditoría',
                'verbose_name_plural': 'Registros de Trazabilidad y Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
