# Generated by Django 5.2.6 on 2025-12-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_some', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_parto', models.CharField(choices=[('vaginal', 'Vaginal'), ('cesarea', 'Cesárea'), ('instrumental', 'Instrumental'), ('extrahospitalario', 'Extrahospitalario')], max_length=20)),
                ('tipo_parto_clasificado', models.CharField(blank=True, max_length=20, null=True)),
                ('complicaciones', models.TextField(blank=True, null=True)),
                ('parto_distocico', models.BooleanField(default=False)),
                ('parto_vacuum', models.BooleanField(default=False)),
                ('rem_a24', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='gestion_some.madre')),
            ],
        ),
        migrations.CreateModel(
            name='RN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('hora_nacimiento', models.TimeField()),
                ('apellido_paterno_rn', models.CharField(max_length=255)),
                ('comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('cesfam', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento_madre', models.DateField(blank=True, null=True)),
                ('tipo_parto', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_parto_clasificado', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('talla', models.IntegerField(blank=True, null=True)),
                ('cc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('semanas_gestacion', models.IntegerField(blank=True, null=True)),
                ('dias_gestacion', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('apego', models.BooleanField(default=False)),
                ('lactancia_antes_60', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=False)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('profesional_vhb', models.CharField(blank=True, max_length=255, null=True)),
                ('apgar_1', models.IntegerField(blank=True, null=True)),
                ('apgar_5', models.IntegerField(blank=True, null=True)),
                ('anomalia_congenita', models.BooleanField(default=False)),
                ('reanimacion_basica', models.BooleanField(default=False)),
                ('reanimacion_avanzada', models.BooleanField(default=False)),
                ('ehi_grado_ii_iii', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rns', to='gestion_some.madre')),
                ('parto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rns', to='partos.parto')),
            ],
        ),
    ]
