# Generated by Django 5.2.6 on 2025-12-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parto',
            name='rem_a24',
        ),
        migrations.RemoveField(
            model_name='rn',
            name='cesfam',
        ),
        migrations.RemoveField(
            model_name='rn',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='rn',
            name='fecha_nacimiento_madre',
        ),
        migrations.RemoveField(
            model_name='rn',
            name='tipo_parto',
        ),
        migrations.RemoveField(
            model_name='rn',
            name='tipo_parto_clasificado',
        ),
    ]
