# Generated by Django 5.2.6 on 2025-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0002_remove_parto_rem_a24_remove_rn_cesfam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado')], default='activo', max_length=20),
        ),
    ]
