# Generated by Django 5.2.8 on 2025-12-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0003_parto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rn',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='parto',
            name='nombre_acompanante',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='tiene_acompanante',
            field=models.BooleanField(default=False, help_text='¿Tiene acompañante?'),
        ),
    ]
