# Generated by Django 5.2.8 on 2025-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0004_remove_rn_confirmado_parto_nombre_acompanante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parto',
            name='tipo_parto_clasificado',
        ),
        migrations.AddField(
            model_name='parto',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso de la madre al evento', null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='hora_ingreso',
            field=models.TimeField(blank=True, help_text='Hora de ingreso de la madre al evento', null=True),
        ),
    ]
