# Generated by Django 5.2.8 on 2025-12-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0005_remove_parto_tipo_parto_clasificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parto',
            name='fecha_hora',
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo_parto',
            field=models.CharField(choices=[('vaginal', 'Vaginal'), ('cesarea_electiva', 'Cesárea Electiva'), ('instrumental', 'Instrumental'), ('cesarea_urgencia', 'Cesárea de Urgencia'), ('extrahospitalario', 'Extrahospitalario')], max_length=20),
        ),
    ]
