# Generated by Django 5.2.8 on 2025-12-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0006_remove_parto_fecha_hora_alter_parto_tipo_parto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto',
            name='tipo_parto',
            field=models.CharField(choices=[('vaginal', 'Vaginal'), ('cesarea_electiva', 'Cesárea Electiva'), ('instrumental', 'Instrumental'), ('cesarea_urgencia', 'Cesárea de Urgencia')], max_length=20),
        ),
    ]
