# Generated by Django 5.2.8 on 2025-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0007_remove_parto_confirmado_alter_parto_tipo_parto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rn',
            name='ehi_grado_ii_iii',
        ),
        migrations.AddField(
            model_name='rn',
            name='ehi_grado',
            field=models.IntegerField(choices=[(0, 'Sin EHI'), (1, 'EHI Grado I (Leve)'), (2, 'EHI Grado II (Moderado)'), (3, 'EHI Grado III (Severo)')], default=0),
        ),
    ]
