# Generated by Django 5.2.8 on 2025-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0008_remove_rn_ehi_grado_ii_iii_rn_ehi_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rn',
            name='reanimacion_avanzada',
        ),
        migrations.RemoveField(
            model_name='rn',
            name='reanimacion_basica',
        ),
        migrations.AddField(
            model_name='rn',
            name='reanimacion',
            field=models.IntegerField(choices=[(0, 'Sin reanimación'), (1, 'Reanimación básica'), (2, 'Reanimación avanzada')], default=0),
        ),
    ]
