# Generated by Django 5.2.8 on 2025-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0009_remove_rn_reanimacion_avanzada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rn',
            name='descripcion_anomalia',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
