# Generated by Django 5.2.8 on 2025-12-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0007_alter_parto_tipo_parto'),
        ('partos', '0010_rn_descripcion_anomalia'),
    ]

    operations = [
    ]
