# Generated by Django 5.2.8 on 2025-12-15 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_some', '0007_remove_madre_fecha_ingreso_remove_madre_hora_ingreso'),
        ('partos', '0007_alter_parto_tipo_parto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REM A24', 'REM A24'), ('REM A02', 'REM A02'), ('REM A10', 'REM A10')], max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_some.madre')),
                ('parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partos.parto')),
                ('rn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partos.rn')),
            ],
        ),
    ]
