# Generated by Django 5.2.6 on 2025-12-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_some', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madre',
            name='acompañante',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='fecha_nacimiento_madre',
        ),
        migrations.AddField(
            model_name='madre',
            name='acompanante',
            field=models.CharField(blank=True, default='Sin Acompañante', max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='antecedentes_obstetricos',
            field=models.TextField(default='Sin antecedentes'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='atenciones_clinicas',
            field=models.TextField(default='Sin atenciones'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='cesfam',
            field=models.CharField(default='Sin CESFAM', max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='comuna',
            field=models.CharField(default='Sin comuna', max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200),
        ),
        migrations.AlterField(
            model_name='madre',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(default='Sin RUT', max_length=12),
        ),
        migrations.AlterField(
            model_name='madre',
            name='telefono',
            field=models.CharField(default='Sin teléfono', max_length=20),
        ),
    ]
