# Generated by Django 5.2.6 on 2025-12-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_some', '0002_remove_madre_acompañante_remove_madre_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='antecedentes_obstetricos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='madre',
            name='atenciones_clinicas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='madre',
            name='cesfam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='madre',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='madre',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='madre',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
