# Generated by Django 5.2.6 on 2025-12-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_some', '0003_alter_madre_antecedentes_obstetricos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='prevision',
            field=models.CharField(choices=[('isapre', 'Isapre'), ('fonasa', 'Fonasa'), ('particular', 'Particular')], default='fonasa', max_length=20),
        ),
    ]
