# Generated by Django 5.2.8 on 2025-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_some', '0004_madre_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='acompanante',
            field=models.CharField(blank=True, default='Sin Acompañante', max_length=100, null=True),
        ),
    ]
