# Generated by Django 5.2.8 on 2025-12-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_some', '0005_alter_madre_acompanante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madre',
            name='acompanante',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='atenciones_clinicas',
        ),
        migrations.AddField(
            model_name='madre',
            name='alergias',
            field=models.BooleanField(default=False, help_text='¿Alergías a Comida/Medicamento?'),
        ),
        migrations.AddField(
            model_name='madre',
            name='alergias_si',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso al sistema', null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='hora_ingreso',
            field=models.TimeField(blank=True, help_text='Hora de ingreso al sistema', null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='migrante',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, help_text='¿Es migrante?'),
        ),
        migrations.AddField(
            model_name='madre',
            name='pueblo_originario',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, help_text='¿Pertenece a pueblo originario?'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='comuna',
            field=models.CharField(help_text='Ej: Los Puelches', max_length=100),
        ),
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
