# Generated by Django 5.2.8 on 2025-12-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_some', '0006_remove_madre_acompanante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madre',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='hora_ingreso',
        ),
    ]
