# Generated by Django 5.2.6 on 2025-12-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('SOME', 'SOME'), ('MATRONA', 'Matrona'), ('SUPERVISOR', 'Supervisor'), ('AUDITORIA', 'Auditoría'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
