# Generated by Django 5.2.8 on 2025-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_customuser_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SOME', 'SOME'), ('MATRONA', 'Matrona'), ('SUPERVISOR', 'Supervisor'), ('AUDITORIA', 'Auditoría'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
